### ISSUE TITLE
More efficient macros for Sidekiq

### ISSUE THREAD

**Issue by adstage-david** [hirefire/hirefire-resource#16]
We're using this plugin to manage a large amount of dynos - one per worker type. We recently started running into problems when we split out from 4 types to 24 types. 

It turns out that when we have a lot of concurrent workers, this starts really bogging down the request for hirefire info - the requests are hitting the Heroku timeout limit, and worse, since hirefire is sending  a request every minute for every type, this can even choke out other requests. 

I think it'd probably run okay if there were options to do the work a little more intelligently so that the loops for the different dynos we want to count only needed to rely on looping through in progress jobs a single time for all of the jobs, instead of once per dyno.

My proposed idea for handling this is adding something like a `HireFire::Resource.dyno_list { |list| ...  }` that'd allow you to define a block capable of counting for multiple dynos simultaneously. I'll throw something together and send a pull request.

**Comment by todddickerson** [comment]
👍 we can't even use hirefire because of this... can't access the sidekiq queue count without timeout..

**Comment by mrrooijen** [comment]
@todddickerson We have a few features in place that may improve performance, i.e. `skip_retries`, `skip_scheduled`, `max_scheduled`. Have you tried any of these yet?

**Comment by todddickerson** [comment]
@mrrooijen nice, didn't see that documented anywhere, looks like it's b/c our schedule has 2mil+ jobs in it, seems to work w/ skip_scheduled

**Comment by mrrooijen** [comment]
@todddickerson cool. If you need to count up to a certain amount of scheduled jobs, you can use `max_scheduled` instead of `skip_scheduled`, then it'll stop counting at whatever number you set `max_scheduled` to.

For example, let's say you have a worker/job ratio of 1:100, with a max of 50 dynos, that means that at 5000 jobs (100*50=5000) you're already running at max dynos. So, if you set `max_scheduled` to `5000` it'll find/count the first `5000` scheduled jobs and skip the rest, returning `5000`, rather than `2,000,000` (which times out), which already causes HireFire to scale up to the max of 50.
