### ISSUE TITLE
HireFire::Macro::Resque.queue counts stale workers

### ISSUE THREAD

**Issue by michieldewit** [hirefire/hirefire-resource#25]
The macro for Resque does not differentiate between working and stale workers. Perhaps it should consider the age of the worker?

**Comment by meskyanichi** [comment]
I wrote a small class a while back with a customer which will prune stale Resque workers. Instead of avoiding the issue, it would be better to periodically prune stale workers. This'll also allow you to avoid zombie-data hogging up your Redis memory.

```rb
class StaleResqueWorkerCleaner
  SLOWEST_JOB = (ENV["RESQUE_SLOWEST_JOB"] || 30).to_i # minutes
 
  def call
    Resque.workers.each do |worker|
      worker.unregister_worker if old_worker?(worker)
    end
  end
 
  private
 
  def old_worker?(worker)
    worker.processing.empty? || 
      Time.now - worker.processing["run_at"].to_time > 60 * SLOWEST_JOB
  end
end

StaleResqueWorkerCleaner.new.call
```

If you know that none of your jobs take more than 30 minutes, you could set this to 30 minutes (default) and it'll unregister any jobs that have been running for > 30 minutes.

You could put this in a Rake task and periodically (hourly, daily) call it using [Heroku Scheduler](https://addons.heroku.com/scheduler).

**Comment by michieldewit** [comment]
Thanks for that. I prefer to use `Resque.size`, although it does not count
the jobs currently being worked on. I combine it with a 5 minutes sliding
maximum to make sure capacity is always sufficient.
