### ISSUE TITLE
App without http server

### ISSUE THREAD

**Issue by kivanio** [hirefire/hirefire-resource#60]
Hi,

We have a Rails app without any http server.
We use it exclusive for jobs/workers.

We would like to autoscale jobs but we could not make it work.
We use Hirefire in others app with http server without any trouble.

Is it possible to use this gem in a Rails app without http server available?

**Comment by mrrooijen** [comment]
Hey,

Currently you do require an http server in order to serve the job queue information. So for now it isn't possible to use hirefire without an http server. In the future we may provide the ability to periodically send data to hirefire rather than having hirefire fetch data, in which case an http server wouldn't be necessary.

This isn't on the roadmap though, so it won't be implemented anytime soon. The simplest thing that you could do is setup bare bones Rack application that only serves hirefire-resource via a single web dyno. Other than that there currently aren't any options available.

**Comment by kivanio** [comment]
ok,
Thank you
